From Cortex Require Import AuthorityModel.
From Cortex Require Import World.
From Cortex Require Import Semantics.
Require Import RelationClasses.
Require Import Relation_Definitions.

(* ================================================================= *
   MODULE: LogicalRelation.v
   ================================================================= *)

Section LogicalRelation.
  Context {A : AuthorityModel}.

  Inductive Ty :=
    | TUnit : Ty
    | TInt  : Ty
    | TCap  : Ty.

  (* Value Relation Interpretation: updated TCap to preserve capability tokens *)
  Definition V_w (t : Ty) (w : World A) (v : Expr) : Prop :=
    match t with
    | TUnit => v = e_val 0
    | TInt  => exists n, v = e_val n
    | TCap  => (exists c, v = e_invoke c /\ valid_cap c w) \/ v = e_val 0
    end.

  (* 
     E_w now directly matches the dynamic world w' generated by the system step,
     completely eliminating the need for an artificial reflexive or speculative world proof.
  *)
  Definition E_w (t : Ty) (w : World A) (cfg : State * Expr) : Prop :=
    forall w' m m' eff cfg',
      step_m w m cfg eff w' m' cfg' ->
      V_w t w' (snd cfg').

  (* Context Lookup Relation using basic nil/cons *)
  Fixpoint lookup (x : nat) (Γ : list Ty) : option Ty :=
    match Γ with
    | nil => None
    | cons t Γ' => match x with
                   | O => Some t
                   | S x' => lookup x' Γ'
                   end
    end.

  (* Semantic Environment Substitution Invariant: w ⊨ γ : Γ *)
  Definition env_valid (w : World A) (Γ : list Ty) (γ : nat -> Expr) : Prop :=
    forall x t, lookup x Γ = Some t -> V_w t w (γ x).

  (* Strong weakening lemma on world parameters of step_m *)
  Lemma step_m_world_weaken : forall w1 w2 w3 m m' cfg eff cfg',
    world_accessible w1 w2 ->
    step_m w2 m cfg eff w3 m' cfg' ->
    step_m w1 m cfg eff w3 m' cfg'.
  Proof.
    intros w1 w2 w3 m m' cfg eff cfg' Hacc12 Hstep.
    inversion Hstep; subst.
    - assert (Hacc13 : world_accessible w1 w3).
      { destruct (@world_accessible_preorder A) as [_ Htrans].
        eapply Htrans; eauto. }
      assert (Hfuel13 : world_fuel w3 < world_fuel w1).
      { destruct Hacc12 as [_ [_ [Hfuel12 _]]].
        eapply lt_le_trans; eauto. }
      eapply step_m_invoke_fresh; eauto.
    - assert (Hacc13 : world_accessible w1 w3).
      { destruct (@world_accessible_preorder A) as [_ Htrans].
        eapply Htrans; eauto. }
      assert (Hfuel13 : world_fuel w3 < world_fuel w1).
      { destruct Hacc12 as [_ [_ [Hfuel12 _]]].
        eapply lt_le_trans; eauto. }
      eapply step_m_invoke_stale; eauto.
  Qed.

  (* Proved Milestone: The Logical Monotonicity Lemma *)
  Lemma E_w_monotonicity (t : Ty) (w1 w2 : World A) (cfg : State * Expr) :
    world_accessible w1 w2 ->
    E_w t w1 cfg ->
    E_w t w2 cfg.
  Proof.
    intros Hacc He1; red; intros w3 m m' eff cfg' Hstep.
    eapply He1.
    eapply step_m_world_weaken; eauto.
  Qed.

End LogicalRelation.
