"""
Cortex Canonical Byte Encoding (CBE) Package
"""

from cortex.cbe.decoder import decode
from cortex.cbe.encoder import encode, encode_python
from cortex.cbe.errors import (
    CBEDuplicateKeyError,
    CBEError,
    CBEFloatNonFiniteError,
    CBEIntOverflowError,
    CBEInvalidLengthError,
    CBEInvalidUTF8Error,
    CBENonCanonicalMapError,
    CBENonNFCError,
    CBEUnknownTagError,
)
from cortex.cbe.normalization import (
    is_nfc_canonical,
    normalize_float,
    normalize_nfc_string,
)
from cortex.cbe.streaming import (
    CBEDataEmptyError,
    CBEFrameError,
    CBEFrameTooLargeError,
    CBEInvalidControlPayloadError,
    CBEMagicMismatchError,
    CBESequenceGapError,
    CBESequenceOverflowError,
    CBETruncatedHeaderError,
    CBETruncatedPayloadError,
    CBEUnknownFrameTypeError,
    CortexFrame,
    FrameType,
    StreamDecoder,
    StreamEncoder,
    decode_frame,
    encode_frame,
)
from cortex.cbe.types import (
    Bool,
    Bytes,
    CortexValue,
    Float,
    Int,
    List,
    Map,
    Null,
    String,
)
from cortex.cbe.vectors import (
    NAMESPACE_CORTEX_SYSTEM,
    VECTORS,
    compute_raw_uuidv5,
    derive_logical_event_id,
)

__all__ = [
    "NAMESPACE_CORTEX_SYSTEM",
    "VECTORS",
    "Bool",
    "Bytes",
    "CBEDuplicateKeyError",
    "CBEError",
    "CBEFloatNonFiniteError",
    "CBEIntOverflowError",
    "CBEInvalidLengthError",
    "CBEInvalidUTF8Error",
    "CBENonCanonicalMapError",
    "CBENonNFCError",
    "CBEUnknownTagError",
    "CBEFrameError",
    "CBEMagicMismatchError",
    "CBEUnknownFrameTypeError",
    "CBEFrameTooLargeError",
    "CBESequenceGapError",
    "CBESequenceOverflowError",
    "CBETruncatedHeaderError",
    "CBETruncatedPayloadError",
    "CBEInvalidControlPayloadError",
    "CBEDataEmptyError",
    "CortexFrame",
    "FrameType",
    "StreamEncoder",
    "StreamDecoder",
    "encode_frame",
    "decode_frame",
    "CortexValue",
    "Float",
    "Int",
    "List",
    "Map",
    "Null",
    "String",
    "compute_raw_uuidv5",
    "decode",
    "derive_logical_event_id",
    "encode",
    "encode_python",
    "is_nfc_canonical",
    "normalize_float",
    "normalize_nfc_string",
]
